### PR TITLE
Update UNS page to use the new tag browser instead of the old data dashboard

### PR DESCRIPTION
**Pull request by ricci2511**
# Description

This PR updates the [Unified Namespace](https://umh.docs.umh.app/docs/features/datainfrastructure/unified-namespace/) page to reflect the new upcoming tag browser, which is intended to replace the current data dashboard.

## Related issues

- Closes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1634

## Checklist

*You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [contributing guidelines](https://umh.docs.umh.app/docs/development/contribute/new-content/add-documentation/) and the [code of conduct](CODE_OF_CONDUCT.md).
- [ ] I have followed the [documentation](https://umh.docs.umh.app/docs/development/contribute/documentation/style/) style.

### CODE REVIEW

**Review by JeremyTheocharis — CHANGES_REQUESTED** [review]
Can you further elaborate on the features that this brings?
 
 1. There is now the schema validation with _historian
 2. It will split a single payload with multiple tags into multiple tags in the view. Also it will allow browsing of a tag folder structure of a single asset
 3. Any unknown schema will show the raw payload
 4. if the schema validation fails, it will show errors
 5. It will also show the fulltagename, which is used to uniqly identify a single tag (independent from the topic and payload structure)
 6. Messages per minute can be used to understand how much is going through that tag
 7. These are still snapshots, so if data is sent in a higher frequency than every 10 seconds, than it might not be correctly displayed
 8.

**Comment by DaruZero** [comment]
I would put this on hold until the tag browser in enabled by default

**Comment by ricci2511** [comment]
> I would put this on hold until the tag browser in enabled by default

I think we should merge this into a tag browser release branch or something similar. So we can push there any other smaller changes that need to be done in the docs regarding the tag browser.

**Comment by DaruZero** [comment]
You can definitely do that. I don't think we are releasing that feature with a minor version increase, but just a patch, so no need to follow the full release workflow. You can create a random chore branch to act as a base for all the other related branches

**Review by JeremyTheocharis — APPROVED** [review]

**Pull request merged**
