### PR TITLE
Tidy up config

### LINKED ISSUE #96: [Chore]: tidy up config.toml
### Describe your feature request for the documentation

At the moment the config file is a bit all over the place, so it need some tidying up

### Describe possible alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by DaruZero**
# Description

Just a little restructuring of the configuration file, removing superfluous fields and reorganize a bit. Also renaming the file to `hugo.toml` as per Hugo recommendation.

## Related issues

Fix #96 

## Checklist

*You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [contributing guidelines](https://umh.docs.umh.app/docs/development/contribute/new-content/add-documentation/) and the [code of conduct](CODE_OF_CONDUCT.md).
- [x] I have followed the [documentation](https://umh.docs.umh.app/docs/development/contribute/documentation/style/) style.

### CODE REVIEW

**Comment by Scarjit** [comment]
```
2023-03-20T09:08:35.027414Z	Cloning repository...
2023-03-20T09:08:35.99841Z	From https://github.com/united-manufacturing-hub/umh.docs.umh.app
2023-03-20T09:08:35.998969Z	 * branch            286058b1771970d965bbc4b5f77f2b1d406c2a11 -> FETCH_HEAD
2023-03-20T09:08:35.999163Z	
2023-03-20T09:08:39.929492Z	Filtering content:  15% (24/154)
Filtering content:  16% (25/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  17% (27/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  18% (28/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  19% (30/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  20% (31/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  21% (33/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  22% (34/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  23% (36/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  24% (37/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  25% (39/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  26% (41/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  27% (42/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  28% (44/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  29% (45/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  30% (47/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  31% (48/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  32% (50/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  33% (51/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  34% (53/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  35% (54/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  36% (56/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  37% (57/154), 13.64 MiB | 22.04 MiB/s
Filtering content:  38% (59/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  39% (61/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  40% (62/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  41% (64/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  42% (65/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  43% (67/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  44% (68/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  45% (70/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  46% (71/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  47% (73/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  48% (74/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  49% (76/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  50% (77/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  51% (79/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  52% (81/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  53% (82/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  54% (84/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  55% (85/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  56% (87/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  57% (88/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  58% (90/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  59% (91/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  60% (93/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  61% (94/154), 16.47 MiB | 13.85 MiB/s
Filtering content:  62% (96/154), 17.15 MiB | 9.79 MiB/s 
Filtering content:  63% (98/154), 17.15 MiB | 9.79 MiB/s
Filtering content:  64% (99/154), 17.15 MiB | 9.79 MiB/s
Filtering content:  65% (101/154), 17.15 MiB | 9.79 MiB/s
Filtering content:  66% (102/154), 17.15 MiB | 9.79 MiB/s
Filtering content:  67% (104/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  68% (105/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  69% (107/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  70% (108/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  71% (110/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  72% (111/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  73% (113/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  74% (114/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  75% (116/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  75% (117/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  76% (118/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  77% (119/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  78% (121/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  79% (122/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  80% (124/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  81% (125/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  82% (127/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  83% (128/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  84% (130/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  85% (131/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  86% (133/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  87% (134/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  88% (136/154), 17.56 MiB | 7.04 MiB/s
Filtering content:  89% (138/154), 26.64 MiB | 9.00 MiB/s
Filtering content:  90% (139/154), 26.64 MiB | 9.00 MiB/s
Filtering content:  91% (141/154), 26.64 MiB | 9.00 MiB/s
Filtering content:  92% (142/154), 26.64 MiB | 9.00 MiB/s
Filtering content:  93% (144/154), 26.64 MiB | 9.00 MiB/s
Filtering content:  94% (145/154), 26.64 MiB | 9.00 MiB/s
Filtering content:  95% (147/154), 26.64 MiB | 9.00 MiB/s
Filtering content:  96% (148/154), 26.64 MiB | 9.00 MiB/s
Filtering content:  97% (150/154), 26.64 MiB | 9.00 MiB/s
Filtering content:  98% (151/154), 26.64 MiB | 9.00 MiB/s
Filtering content:  99% (153/154), 26.64 MiB | 9.00 MiB/s
Filtering content: 100% (154/154), 26.64 MiB | 9.00 MiB/s
Filtering content: 100% (154/154), 26.75 MiB | 7.55 MiB/s, done.
2023-03-20T09:08:39.930089Z	HEAD is now at 286058b Merge branch 'main' into chore/96/tidy-up-config
2023-03-20T09:08:39.930279Z	
2023-03-20T09:08:41.29499Z	Submodule 'umh.docs.umh.app/themes/docsy' (https://github.com/google/docsy) registered for path 'umh.docs.umh.app/themes/docsy'
2023-03-20T09:08:41.295561Z	Cloning into '/opt/buildhome/clone/umh.docs.umh.app/themes/docsy'...
2023-03-20T09:08:41.295743Z	Submodule path 'umh.docs.umh.app/themes/docsy': checked out '5597d435dc74ce68240e0c3871addf24567493b0'
2023-03-20T09:08:41.295876Z	
2023-03-20T09:08:41.329012Z	Success: Finished cloning repository files
2023-03-20T09:08:42.046373Z	Installing dependencies
2023-03-20T09:08:42.057192Z	Python version set to 2.7
2023-03-20T09:08:45.712185Z	Downloading and installing node v16.17.0...
2023-03-20T09:08:46.175445Z	Downloading https://nodejs.org/dist/v16.17.0/node-v16.17.0-linux-x64.tar.xz...
2023-03-20T09:08:46.603607Z	Computing checksum with sha256sum
2023-03-20T09:08:46.737452Z	Checksums matched!
2023-03-20T09:08:51.194693Z	Now using node v16.17.0 (npm v8.15.0)
2023-03-20T09:08:51.641313Z	Started restoring cached build plugins
2023-03-20T09:08:51.654931Z	Finished restoring cached build plugins
2023-03-20T09:08:52.201564Z	Attempting ruby version 2.7.1, read from environment
2023-03-20T09:08:55.866452Z	Using ruby version 2.7.1
2023-03-20T09:08:56.220882Z	Using PHP version 5.6
2023-03-20T09:08:56.379142Z	5.2 is already installed.
2023-03-20T09:08:56.408499Z	Using Swift version 5.2
2023-03-20T09:08:56.408836Z	Installing Hugo v0.85.0
2023-03-20T09:08:57.779614Z	hugo v0.85.0-724D5DB5+extended linux/amd64 BuildDate=2021-07-05T10:46:28Z VendorInfo=gohugoio
2023-03-20T09:08:57.784149Z	Started restoring cached go cache
2023-03-20T09:08:57.802839Z	Finished restoring cached go cache
2023-03-20T09:08:57.94685Z	go version go1.14.4 linux/amd64
2023-03-20T09:08:57.962593Z	go version go1.14.4 linux/amd64
2023-03-20T09:08:57.965356Z	Installing missing commands
2023-03-20T09:08:57.965588Z	Verify run directory
2023-03-20T09:08:57.965824Z	Executing user command: git lfs install && git submodule update -f --init --recursive && cd umh.docs.umh.app/themes/docsy && npm install && cd ../.. && npm install postcss-cli autoprefixer && [[ $SKIP_IMAGE_OPTIMIZATION = false ]] && (cd ./static/images && npx --yes avif --overwrite --verbose --input="**/*.{jpg,png}" && cd ../..) || echo "Skipping image optimization" && hugo --gc --minify
2023-03-20T09:08:58.049279Z	Updated git hooks.
2023-03-20T09:08:58.049579Z	Git LFS initialized.
2023-03-20T09:08:58.40529Z	Submodule path 'umh.docs.umh.app/themes/docsy': checked out '5597d435dc74ce68240e0c3871addf24567493b0'
2023-03-20T09:09:03.322483Z	npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
2023-03-20T09:09:06.473592Z	
2023-03-20T09:09:06.473937Z	added 178 packages, and audited 179 packages in 8s
2023-03-20T09:09:06.474113Z	
2023-03-20T09:09:06.474231Z	42 packages are looking for funding
2023-03-20T09:09:06.474354Z	  run `npm fund` for details
2023-03-20T09:09:06.475129Z	
2023-03-20T09:09:06.475381Z	found 0 vulnerabilities
2023-03-20T09:09:09.57206Z	
2023-03-20T09:09:09.572805Z	added 74 packages, and audited 75 packages in 3s
2023-03-20T09:09:09.573169Z	
2023-03-20T09:09:09.57332Z	18 packages are looking for funding
2023-03-20T09:09:09.57368Z	  run `npm fund` for details
2023-03-20T09:09:09.573861Z	
2023-03-20T09:09:09.574284Z	found 0 vulnerabilities
2023-03-20T09:09:09.585325Z	Skipping image optimization
2023-03-20T09:09:09.623949Z	Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
2023-03-20T09:09:09.624249Z	       Run `hugo help new` for details.
2023-03-20T09:09:09.624407Z	
2023-03-20T09:09:09.624572Z	Total in 1 ms
2023-03-20T09:09:09.631515Z	Failed: build command exited with code: 255
2023-03-20T09:09:10.851416Z	Failed: an internal error occurred
```

**Comment by DaruZero** [comment]
Please update Hugo to latest version in CF

**Comment by JeremyTheocharis** [comment]
Which version do you want me to set it to? Please also note this: 
https://developers.cloudflare.com/pages/platform/known-issues/#build-configuration

image

**Comment by DaruZero** [comment]
It's weird because these lines in the logs says that it's installing Hugo v0.85.0
```
2023-03-20T09:08:56.408836Z	Installing Hugo v0.85.0
2023-03-20T09:08:57.779614Z	hugo v0.85.0-724D5DB5+extended linux/amd64 BuildDate=2021-07-05T10:46:28Z VendorInfo=gohugoio
```

Version v0.111.3 should be fine, I don't know why CF is ignoring the env variable and just installing an older version

**Comment by Scarjit** [comment]
@JeremyTheocharis I already upgraded it, thats why i reacted to the msg

**Review by JeremyTheocharis — APPROVED** [review]

**Pull request merged**
