### PR TITLE
Updated shopfloor section

### PR DESCRIPTION
**Pull request by Scarjit**
Closes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1616

### CODE REVIEW

**Review by JeremyTheocharis — CHANGES_REQUESTED** [review]
1. Don't we need to change more stuff on this page here, e.g. about how the entire OEE calculation works in the new logic? --> maybe set this page to draft until we have all that information. Or is this another PR?
2. the order in the menu looks a little bit unintuitive. would it maybe make sense to have as a suboage of analytics the old analytics? (deprecated: shopfloor KPIs in data model v0)

image

Also I think this should be merged into a branch for when we actually release it and not go live immediately, right?

**Review by JeremyTheocharis — CHANGES_REQUESTED** [review]
Can you stack the PRs so that it gets easier to review? also probably some stuff needs to be adjusted based on the latest database schema

**Comment by Scarjit** [comment]
@JeremyTheocharis I moved both in the same folder.
image

What do you think ?

**Review by JeremyTheocharis — APPROVED** [review]
looks reasonable, but is not important right now for shipping the "storing in _analytics tables" feature

**Pull request merged**
