### PR TITLE
Feat/969/data model v2 phase 3

### PR DESCRIPTION
**Pull request by JeremyTheocharis**
# Description

Documentation for https://github.com/united-manufacturing-hub/MgmtIssues/issues/969 for the Data Model v2 Phase 3

Closes https://github.com/united-manufacturing-hub/MgmtIssues/issues/1705

## Checklist

*You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [contributing guidelines](https://umh.docs.umh.app/docs/development/contribute/new-content/add-documentation/) and the [code of conduct](CODE_OF_CONDUCT.md).
- [x] I have followed the [documentation](https://umh.docs.umh.app/docs/development/contribute/documentation/style/) style.

### CODE REVIEW

**Comment by JeremyTheocharis** [comment]
Review it :)

**Comment by JeremyTheocharis** [comment]
And can you remove the link checker? it is running unnecessary long (and therefore causing costs): 
image

**Review by Scarjit — APPROVED** [review]

**Comment by Scarjit** [comment]
cfp pls

**Comment by Scarjit** [comment]
@JeremyTheocharis See also https://github.com/united-manufacturing-hub/ManagementConsole/pull/526
CF pages seems to be down (well it deploys but not reporting status)

**Pull request merged**
